# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.magosa.pl" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Krzysztof Magosa - Blog
  avatar: avatar.png
  gravatar: 5c766b0b1d51e16074a4f59c8392e20d # Email MD5 hash
  description: "Krzysztof Magosa - Blog" # used by search engines

  # Header and footer text
  header_text: >
    Blog about software and systems engineering
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: krzysztof@magosa.pl # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "krzysztof-magosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/krzysztofmagosa # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "k_magosa"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-52561301-4" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "krzysztofmagosablog"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
#markdown: kramdown

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
